"""
Day 06
Date: 26th April 2022 Tuesday
Name: kavuri venkatesh reddy
File Desc:Sep_end methods
"""
# print(' '.isspace()) #True
# print(''.isspace()) #False
# print('A'.isspace()) #False

# print('Hello'+'World') #HelloWorld
# print('Hello','World') #Hello World
# print('Hello'+''+'World') #HelloWorld
# print('Hello'+' '+'World') #HelloWorld
# print('Hello'+'-'+'World') #Hello-World

# print("Welcome","To","Python",sep='') #WelcomeToPython
# print("Welcome","To","Python",sep=' ') #Welcome To Python
# print("Welcome","To","Python",sep='-') #Welcome-To-Python

# print("Welcome",end=" ")
# print("to",end=" ")
# print("python",end=".") #Welcome to python

# print("welcome",end=" ")
# print("to",sep=" ")
# print("python")
#welcome to
#python

# print("welcome","to","python","course",sep=" ",end=".")
# print("in","josh innovations",end=".",sep=" ")
